jfrog/terraform-provider-project

go.mod
go.sum
pkg/projects/resource_project.go
pkg/projects/resource_project_membership.go
pkg/projects/resource_project_repo.go
pkg/projects/resource_project_role.go
pkg/projects/resource_project_role_test.go

Using [errgroup](https://pkg.go.dev/golang.org/x/sync/errgroup) to manage error returning. Open to use other packages/patterns since I'm new to GoRoutine.

First pass at applying async for sub-resources

---

TFproviderTest.yml

The final version. We need to merge it to master to run the final test.

Pipelines file update

---

CHANGELOG.md
pkg/projects/resource_project.go
pkg/projects/resource_project_membership.go
pkg/projects/resource_project_role.go
pkg/projects/resource_project_test.go
pkg/projects/util_test.go
pkg/projects/validators.go

closes #22 
Project key validation is fixed as per latest Artifactory release version.

Project Key Validation fixed

---

GNUmakefile
go.mod
main.go
pkg/project/provider.go
pkg/project/provider_test.go
pkg/project/resource_project.go
pkg/project/resource_project_membership.go
pkg/project/resource_project_membership_test.go
pkg/project/resource_project_repo.go
pkg/project/resource_project_repo_test.go
pkg/project/resource_project_role.go
pkg/project/resource_project_role_test.go
pkg/project/resource_project_test.go
pkg/project/util.go
pkg/project/util_test.go
pkg/project/validators.go

The package name changed to singular to match the repo name (fixes `go get` failure)
Added GOPROXY in release function in Makefile
Added Update package cache function

Replacing plural name with singular, add update package cache function

---

TFproviderTest.yml
pkg/project/util_test.go

Remove cancelPendingRunsOn PR modified event.
Update Go version to 1.18
Truncate PR title for Slack notification

Pipeline, add Artifactory and Xray versions to CHANGELOG.md

---

CHANGELOG.md
pkg/project/resource_project_repo_test.go
pkg/project/util_test.go

Add PR links to the CHANGELOG.md

Fix the error in the password field in user struct

---

GNUmakefile
go.mod
go.sum
pkg/project/provider.go
pkg/project/provider_test.go

And use funcs from shared module. Fix incorrect package path in make file.

Improve telemetry

---

CHANGELOG.md
GNUmakefile
go.mod
go.sum
pkg/project/provider.go

To ensure correct HTTP user-agent is used
Fixes https://github.com/jfrog/terraform-provider-shared/issues/17

Switch to pass productId to shared module

---

CHANGELOG.md
go.mod
go.sum
pkg/project/resource_project.go
pkg/project/resource_project_test.go

Fixes https://github.com/jfrog/terraform-provider-shared/issues/21

Update project_key validation and tests

---

CHANGELOG.md
docs/resources/project.md
pkg/project/resource_project.go
pkg/project/resource_project_test.go

Add recommendation note to repos attribute

---

CHANGELOG.md
docs/resources/project.md
pkg/project/resource_project.go

Thanks for suggestion from @oallauddin https://github.com/jfrog/terraform-provider-project/issues/58#issuecomment-1319445493
You can preview the content by copy/paste into Terraform's [Doc Preview tool](https://registry.terraform.io/tools/doc-preview).

Add more details on repository configuration to documentation

---

CHANGELOG.md
docs/guides/repositories_in_project.md

The guide will be shown as a separate category in the Terraform registry documentation.

Added a guide on adding repositories to the project.

---

docs/index.md

Added a few lines of documentation on how to import an existing project.

Added documentation on importing existing projects

---

pkg/project/resource_project.go

This belongs to this PR: https://github.com/jfrog/terraform-provider-shared/pull/23 and fixes the description if you decide to merge PR in terraform-provider-shared.

Fixing the projectSchema key description

---

CHANGELOG.md
docs/resources/project.md
go.mod
go.sum
pkg/project/resource_project.go
pkg/project/resource_project_test.go

* Update go.mod to use latest shared lib
* Update tests to follow new projectKey validation
For https://github.com/jfrog/terraform-provider-shared/pull/23

Update key validation

---

CHANGELOG.md
pkg/project/resource_project.go
pkg/project/resource_project_test.go

Fixes #62 
- Project API's value is opposite of this attribute (and web UI as well).
- Add update and import tests

Flip boolean packing/unpacking of block_deployments_on_limit

---

.gitignore
GNUmakefile
sonar-project.properties

Add SonarQube scan configuration

PTRENG-4787 add SonarQube

---

.github/release.yml
.goreleaser.yml
CHANGELOG.md
go.mod
go.sum
pkg/project/resource_project.go
pkg/project/resource_project_test.go
pkg/project/util.go
pkg/project/validators.go

Close #79 
So 32 bit platform would still work
Add validation for min and max
Remove unused func

Use int64 explicitly with max_storage_in_gibibytes

---

CHANGELOG.md
docs/resources/environment.md
docs/resources/role.md
examples/resources/project_environment/import.sh
examples/resources/project_role/import.sh

Update import example for project_environment doc

Add missing import example to project_role doc

---

CHANGELOG.md
pkg/project/repo.go
pkg/project/resource_project.go
pkg/project/resource_project_test.go
pkg/project/util.go
terraform-registry-manifest.json

Tidy up other retry logic code
Replace programmatic API calls for repo, user, group with Terraform configuration 
Fix invalid JSON for TF registry manifest
Close #96

Add retry logic for project deletion

---

CHANGELOG.md
pkg/project/resource_project_repository.go
sample.tf

Add retry logic for project_repository create func

---

.github/workflows/acceptance-tests.yml
.gitignore
.goreleaser.yml
GNUmakefile
README.md
go.mod
scripts/system.yaml

Update makefile to allow execution with OpenTofu

Add GitHub Workflow for acceptance testings

---

.github/workflows/acceptance-tests.yml
CHANGELOG.md
pkg/project/resource/resource_project_repository_test.go
pkg/project/resource/resource_project_test.go
pkg/project/resource/resource_project_user_test.go

Add workflow conditions to ensure clean up and status steps are always executed

Fix artifactory provider version in some tests for OpenTofu
